
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DocumentApp_ProizvodstvennayaPraktika
{

using System;
    using System.Collections.Generic;
    
public partial class ClientDetails
{

    public int ClientDetailId { get; set; }

    public int UserId { get; set; }

    public string PassportNumber { get; set; }

    public string PassportIssuedBy { get; set; }

    public Nullable<System.DateTime> PassportIssueDate { get; set; }

    public string Address { get; set; }

    public string Organization { get; set; }

    public string Position { get; set; }

    public string BankDetails { get; set; }



    public virtual Users Users { get; set; }

}

}
