
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DocumentApp_ProizvodstvennayaPraktika
{

using System;
    using System.Collections.Generic;
    
public partial class ContractTemplates
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ContractTemplates()
    {

        this.ClientContracts = new HashSet<ClientContracts>();

        this.TemplateFields = new HashSet<TemplateFields>();

    }


    public int TemplateId { get; set; }

    public string TemplateName { get; set; }

    public string Description { get; set; }

    public string Content { get; set; }

    public int CreatedBy { get; set; }

    public Nullable<System.DateTime> CreatedAt { get; set; }

    public Nullable<System.DateTime> UpdatedAt { get; set; }

    public Nullable<bool> IsActive { get; set; }

    public int CategoryId { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ClientContracts> ClientContracts { get; set; }

    public virtual ContractCategories ContractCategories { get; set; }

    public virtual Users Users { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TemplateFields> TemplateFields { get; set; }

}

}
