
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DocumentApp_ProizvodstvennayaPraktika
{

using System;
    using System.Collections.Generic;
    
public partial class ContractHistory
{

    public int HistoryId { get; set; }

    public int ContractId { get; set; }

    public int ChangedBy { get; set; }

    public Nullable<System.DateTime> ChangeDate { get; set; }

    public string ChangeDescription { get; set; }

    public string OldData { get; set; }

    public string NewData { get; set; }



    public virtual ClientContracts ClientContracts { get; set; }

    public virtual Users Users { get; set; }

}

}
