
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DocumentApp_ProizvodstvennayaPraktika
{

using System;
    using System.Collections.Generic;
    
public partial class TemplateFields
{

    public int FieldId { get; set; }

    public int TemplateId { get; set; }

    public string FieldName { get; set; }

    public string FieldLabel { get; set; }

    public string FieldType { get; set; }

    public Nullable<bool> IsRequired { get; set; }

    public string DefaultValue { get; set; }

    public Nullable<int> OrderIndex { get; set; }

    public string ValidationPattern { get; set; }



    public virtual ContractTemplates ContractTemplates { get; set; }

}

}
